name: omphalos_warehouse
version: 1.0.0
config-version: 2
profile: omphalos

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

models:
  omphalos_warehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
