"""
PDF export for omphalOS packets.

Generates formatted PDF reports from packet JSON for distribution to stakeholders.
Uses reportlab for PDF generation (install: pip install reportlab --break-system-packages)
"""

import json
from pathlib import Path
from datetime import datetime

def generate_pdf_report(packet_path: str | Path, output_path: str | Path):
    """
    Generate PDF report from packet JSON.

    Args:
        packet_path: Path to packet.json
        output_path: Path for generated PDF

    Note: This is a placeholder implementation. Production deployment requires:
        - pip install reportlab --break-system-packages
        - Full report template with tables, charts
        - BIS/OFAC house style formatting
    """
    packet_path = Path(packet_path)
    output_path = Path(output_path)

    # Read packet
    with open(packet_path, 'r', encoding='utf-8') as f:
        packet = json.load(f)

    # For now, generate Markdown report (can be converted to PDF via pandoc)
    markdown_report = generate_markdown_report(packet)

    # Write markdown version
    md_path = output_path.with_suffix('.md')
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(markdown_report)

    print(f"Markdown report generated: {md_path}")
    print("To convert to PDF, run: pandoc report.md -o report.pdf")

    return str(md_path)

def generate_markdown_report(packet: dict) -> str:
    """Generate Markdown-formatted report from packet."""

    report = f"""# omphalOS Analytical Packet

**Case ID**: {packet['case_id']}
**Run ID**: {packet['run_id']}
**Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

---

## Executive Summary

{packet['memo']}

---

## Claims

### Observations

"""

    # Add observations
    observations = [c for c in packet['claims'] if c['type'] == 'observation']
    if observations:
        for obs in observations:
            report += f"- {obs['text']}\n"
    else:
        report += "*No observations recorded.*\n"

    report += "\n### Unknowns\n\n"

    # Add unknowns
    unknowns = [c for c in packet['claims'] if c['type'] == 'unknown']
    if unknowns:
        for unk in unknowns:
            report += f"- {unk['text']}\n"
    else:
        report += "*No unknowns recorded.*\n"

    # Add annexes
    report += "\n---\n\n## Annexes\n\n"

    if packet.get('annexes'):
        for key, value in packet['annexes'].items():
            report += f"### {key.replace('_', ' ').title()}\n\n"
            if isinstance(value, list) and value and isinstance(value[0], dict):
                # Format as table
                report += "| " + " | ".join(value[0].keys()) + " |\n"
                report += "| " + " | ".join(['---'] * len(value[0])) + " |\n"
                for row in value:
                    report += "| " + " | ".join(str(v) for v in row.values()) + " |\n"
                report += "\n"
            else:
                report += f"```json\n{json.dumps(value, indent=2)}\n```\n\n"

    # Add tables reference
    if packet.get('tables'):
        report += "---\n\n## Data Tables\n\n"
        for table in packet['tables']:
            report += f"- **{table.get('name', 'Unnamed')}**: {table.get('note', 'No description')}\n"

    # Add footer
    report += f"""
---

## Methodology

This packet was generated by omphalOS, a polycentric, offline-capable casework suite for export control analysis.

**Verification**: Run checksums validated by independent Rust and Go verifiers.
**Reproducibility**: Run artifacts enable bit-identical re-execution.
**Transparency**: All investigations are human-readable SQL, version-controlled.

For questions about this analysis, contact the analyst team.

---

*Co-Authored-By: omphalOS v1.0*
"""

    return report

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python export_pdf.py <packet.json> <output.pdf>")
        sys.exit(1)

    generate_pdf_report(sys.argv[1], sys.argv[2])
